config/routes.rb
require 'resque/server'

FeedEngine::Application.routes.draw do
  mount Resque::Server, at: "/resque"

  match '/', to: 'feeds#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www'}
  get  "/dashboard" =>"users#show", :as => 'dashboard'

  resources :feeds do
    resources :searches
  end

  resources :sessions
  resources :users, only: [:new, :create, :edit, :update]

  root to: 'sessions#home'


  match 'auth/:provider/callback', to: 'sessions#create'
  # match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :provider, :provider_id, :username, :email
  has_many :feeds


  def self.parse_user_info(omni_auth_hash)
    username    = omni_auth_hash['info']['nickname']
    provider    = omni_auth_hash['provider']
    provider_id = omni_auth_hash['uid']

    {username: username, provider: provider, provider_id: provider_id}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    user_details_from_form = params[:user]
    @user = User.create(user_details_from_form.merge(session[:user_info]))
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
      UserMailer.signup_confirmation(@user).deliver
    else
      redirect_to root_url(:subdomain => false), notice: "Login failed"
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.update_attributes(:email => params[:user][:email])
    redirect_to dashboard_path
  end

  def show
    @user = current_user
    @feeds = @user.feeds
  end
end

app/views/users/_form.html.erb
<%= form_for @user, html: { class:'form-inline' } do |f| %>

      <%= f.text_field :email %>
      <%= f.hidden_field :username %>

      <%= f.submit "Submit", class:'btn btn-primary' %>
    <% end %>

app/views/users/edit.html.erb
<div class="content">
  <div id='email-form'>
    <h3>Edit Email Address</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="content">
  <div id='email-form'>
    <h3 id="email">We need your email to complete the signup process.</h3><br>
    <div id="email_form"><%= render 'form' %><div>
  </div>
</div>

app/views/users/show.html.erb
 <div class='content user-show'>

  <%= link_to "Create A New Feed", new_feed_path, id: 'newfeedbutton', class: 'btn btn-inverse' %>

  <ul class='nav nav-tabs'>
    <li class='active'><a href="#manageFeeds" data-toggle="tab">Manage Feeds</a></li>
    <li><a href="#myAccount" data-toggle="tab">My Account</a></li>
  </ul>
   <div class='tab-content'>

      <div class="tab-pane active" id='manageFeeds'>

          <div class="container-fluid">
              <% if @feeds.present? %>
              <% @feeds.each do |feed| %>
            <div class="row-fluid">
              <div class="span2">
                <h4><%= feed.name %></h4>
                <p> Visit Your Feed: <%= link_to feed.subdomain+'.photoline-feed.us/', root_url(subdomain: feed.subdomain) %></p>
                <%= button_to "Delete", {:controller => :feeds, :action => 'destroy', :id => feed.id }, :method => :delete, class:'btn btn-danger', confirm: 'Are you sure?' %>
              </div>
              <div class="span10">
                <h3>Feed Sampling</h3>
                      <% feed.feed_items[0..9].each do |feed|%>
                        <%= image_tag(feed.photo_url, :size => "200x200") %>
                      <%end %>

                      <% if feed.searches.any? %>
                        <table class="table table-striped">
                        <tbody>
                        <thead>
                      </thead>

                      <% feed.searches.each do |search| %>
                        <tr>
                        </tr>
                      <% end %>
                    </div>
                    </div>
                  </div>
                        </tbody>
                        </table>
                  <% end %>
            </div>
          </div>
          <hr>
          </tbody>
          </table>
          <% end %>

        <% else %>
            You Don't Have Any Feeds Yet! Create One.
        <% end %>
      </div>
    </div>
        <div class='tab-pane' id='myAccount'>
          <h1> Account Information For:
              <span id= 'username'> <%= @user.username %> </span>
          </h1>

          <p> Your email address: <%= @user.email %></p>
          <p><%= link_to 'Update Email', edit_user_path(current_user.id) %></p>
          <% link_to "Disable Your Account", root_path %>
        </div>
    </div>
  </div>

</div>