config/routes.rb
require 'resque/server'

FeedEngine::Application.routes.draw do
  mount Resque::Server, at: "/resque"

  match '/', to: 'feeds#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www'}
  get  "/dashboard" =>"users#show", :as => 'dashboard'

  resources :feeds do
    resources :searches
  end

  resources :sessions
  resources :users, only: [:new, :create, :edit, :update]

  root to: 'sessions#home'


  match 'auth/:provider/callback', to: 'sessions#create'
  # match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/views/layouts/_menu.html.erb
<!-- <div class="menu-trigger">Menu</div> -->
  <div class="menu-trigger"><%= image_tag("person.png") %></div>
  <ul id="menu" style="display: none;">
    <div id="user">Signed in as <%= current_user.username %></div>
    <li><%= link_to "Feeds", "#" %></li><br>
    <li><%= link_to "Dashboard", dashboard_path %></li><br>
    <li><%= link_to "New Feed", new_feed_path %></li><br>
    <li><%= link_to "Sign out", signout_path %></li>
  </ul>

<script type="text/javascript">
  $(document).ready(function () {
    var jPM = $.jPanelMenu();
    jPM.on();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedEngine</title>
  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= javascript_include_tag "application", "http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Metrophobic' rel='stylesheet' type='text/css'>

</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <%= render "shared/user_navigation" %>
        <p id="logo"><%= link_to "Photoline", root_url(:subdomain => false) %></p>
      </div>
    </div>
  </div>
     <% if flash[:notice] %>
    <div class='flash'><%= flash[:notice] %></div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/layouts/full_screen_photo_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedEngine</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans+Caption' rel='stylesheet' type='text/css'>

  <%= javascript_include_tag "application", "http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Metrophobic' rel='stylesheet' type='text/css'>

</head>

<body>
  <% if flash[:notice] %>
    <div class='flash'><%= flash[:notice] %></div>
  <% end %>


  <%= yield %>

</body>
</html>